# NAME: selfdirect
# AUTHOR: kjxing
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2024-07-03 16:16:17
# DOMAIN-SUFFIX: 259
# TOTAL: 259
payload:
  - DOMAIN-SUFFIX,pacific-gas.com
  - DOMAIN-SUFFIX,pgnewbuilding.com
  - DOMAIN-SUFFIX,office365.com
  - IP-CIDR,213.35.100.0/8
  - IP-CIDR,140.245.110.0/8
  - IP-CIDR,150.230.39.0/8
  - IP-CIDR,192.9.231.0/8
  - IP-CIDR,192.9.227.0/8
